### ISSUE TITLE
UITest Android 10 cannot restart app or call backdoors after phone contact picker is opened

### ISSUE THREAD

**Issue by VincentH-Net** [microsoft/appcenter#1036]
In Test Cloud, after opening the phone contact picker from the app that is tested, I need to restart the app because that is the only way UITest lets me exit the phone contact picker.

Restart works on iOS 10 - 12 and Android 6 - 9 when the contact picker is open, but not on Android 10 (Google Pixel 3a).

Please fix this - **or even better, provide a way to return to the app after system UI like the contact picker was opened**.

On Android 10 app restart fails, and backdoor methods also fail. All subsequent tests in the test run fail and the contact picker remains open:

![image](https://user-images.githubusercontent.com/1872271/65037443-fc4b1900-d94d-11e9-9d1e-03f37f5a4f7e.png)

A workaround is to ensure that this test is last in a test run. However that won't work when you have more than one test of this type.

When restarting the app, the UITest log says:
```
1) Error : Wsp.Anywhere365.Bridg.UITests.Tests.XDialerTests.CallContacts
System.Net.WebException : POST Failed
TearDown : System.Net.WebException : POST Failed
  at Xamarin.UITest.Shared.Http.HttpClient.HandleHttpError (System.String method, System.Exception exception, Xamarin.UITest.Shared.Http.ExceptionPolicy exceptionPolicy) [0x0003c] in <a0c3f09cbf9049cbb8d3a680a53dcf46>:0 
  at Xamarin.UITest.Shared.Http.HttpClient.SendData (System.String endpoint, System.String method, System.Net.Http.HttpContent content, Xamarin.UITest.Shared.Http.ExceptionPolicy exceptionPolicy, System.Nullable`1[T] timeOut) [0x0013d] in <a0c3f09cbf9049cbb8d3a680a53dcf46>:0 
  at Xamarin.UITest.Shared.Http.HttpClient.Post (System.String endpoint, System.String arguments, Xamarin.UITest.Shared.Http.ExceptionPolicy exceptionPolicy, System.Nullable`1[T] timeOut) [0x00014] in <a0c3f09cbf9049cbb8d3a680a53dcf46>:0 
  at Xamarin.UITest.Shared.Android.HttpApplicationStarter.Execute (System.String intentJson) [0x00035] in <a0c3f09cbf9049cbb8d3a680a53dcf46>:0 
  at Xamarin.UITest.Shared.Android.AndroidAppLifeCycle.LaunchApp (System.String appPackageName, Xamarin.UITest.Shared.Android.ApkFile testServerApkFile, System.Int32 testServerPort) [0x000a1] in <a0c3f09cbf9049cbb8d3a680a53dcf46>:0 
  at Xamarin.UITest.Shared.Android.AndroidAppLifeCycle.LaunchApp (Xamarin.UITest.Shared.Android.ApkFile appApkFile, Xamarin.UITest.Shared.Android.ApkFile testServerApkFile, System.Int32 testServerPort) [0x00007] in <a0c3f09cbf9049cbb8d3a680a53dcf46>:0 
  at Xamarin.UITest.Android.AndroidApp..ctor (Xamarin.UITest.Configuration.IAndroidAppConfiguration appConfiguration, Xamarin.UITest.Shared.Execution.IExecutor executor) [0x00193] in <a0c3f09cbf9049cbb8d3a680a53dcf46>:0 
  at Xamarin.UITest.Android.AndroidApp..ctor (Xamarin.UITest.Configuration.IAndroidAppConfiguration appConfiguration) [0x00000] in <a0c3f09cbf9049cbb8d3a680a53dcf46>:0 
  at Xamarin.UITest.Configuration.AndroidAppConfigurator.StartApp (Xamarin.UITest.Configuration.AppDataMode appDataMode) [0x00017] in <a0c3f09cbf9049cbb8d3a680a53dcf46>:0 
  at Wsp.Anywhere365.Bridg.UITests.AppInitializer.ConfigureAppForTestCloud (System.Boolean clearData) [0x00013] in <6d75cad6c27f4787b545d5589cde6739>:0 
  at Wsp.Anywhere365.Bridg.UITests.AppInitializer.StartApp (Xamarin.UITest.Platform platform, System.Boolean clearData, System.Boolean isTestSessionStart) [0x00017] in <6d75cad6c27f4787b545d5589cde6739>:0 
  at Wsp.Anywhere365.Bridg.UITests.Tests.BaseTests.RestartApp (System.Boolean clearData) [0x00001] in <6d75cad6c27f4787b545d5589cde6739>:0 
  at Wsp.Anywhere365.Bridg.UITests.Tests.XDialerTests.CallContacts () [0x00025] in <6d75cad6c27f4787b545d5589cde6739>:0 
```

When calling a logging backdoor function, the device log shows `java.util.EmptyStackException at java.util.Stack.peek(Stack.java:102)`:

```
I/System.out(11890): URI: /backdoor
I/System.out(11890): params: {json={"method_name":"TraceOnDevice","arguments":["16-42-2019 02:42:32.324 +00:00 RestartApp: Restarting... at Bridg.UITests/Tests/BaseTests.cs:32"]}
I/System.out(11890): }
W/System.err(11890): java.util.EmptyStackException
W/System.err(11890): 	at java.util.Stack.peek(Stack.java:102)
W/System.err(11890): 	at sh.calaba.instrumentationbackend.CalabashInstrumentation.getLastActivity(CalabashInstrumentation.java:38)
W/System.err(11890): 	at sh.calaba.instrumentationbackend.entrypoint.ApplicationUnderTestInstrumentation.getCurrentActivity(ApplicationUnderTestInstrumentation.java:31)
W/System.err(11890): 	at sh.calaba.instrumentationbackend.entrypoint.ApplicationUnderTestInstrumentation.getApplication(ApplicationUnderTestInstrumentation.java:20)
W/System.err(11890): 	at sh.calaba.instrumentationbackend.automation.CalabashAutomationEmbedded.getCurrentApplication(CalabashAutomationEmbedded.java:27)
W/System.err(11890): 	at sh.calaba.instrumentationbackend.actions.HttpServer.serve(HttpServer.java:392)
W/System.err(11890): 	at sh.calaba.instrumentationbackend.actions.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:487)
W/System.err(11890): 	at java.lang.Thread.run(Thread.java:919)
```

**Comment by jwargo** [comment]
@VincentH-Net have you discussed this issue with our support team? There should be an easier way to do this. In the mean time, I'll discuss this issue with the product's Program Manager to learn what I can about potential solutions.

**Comment by VincentH-Net** [comment]
@jwargo I asked the support team just now for an easier way to do this (it seems a bit weird though, reporting an issue on github and then pointing out to the support team in a chat that the issue exists - shouldn't they be monitoring this repo's issues?)

I'assuming that solving the issue as I reported it here will be through your follow up. Thanks!

**Comment by Oddj0b** [comment]
@VincentH-Net I'll close the issue and assume our support team handled it.

**Comment by VincentH-Net** [comment]
@Oddj0b Hi, the issue still exists; I re-tested this yesterday with a Google Pixel 3a on Android 9 and Android 10. You can see that the restart still does not work on Android 10, the Contacts picker stays open:
![image](https://user-images.githubusercontent.com/1872271/66383439-49eefa80-e9bd-11e9-8c61-72b13e71550f.png)

The support team said they would file the issue with the engineering team

**Comment by Oddj0b** [comment]
@VincentH-Net Good point, I'll keep it open.

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
