### ISSUE TITLE
Support .net core 3.0

### ISSUE THREAD

**Issue by imatviienkoomcinc** [microsoft/appcenter#1531]
Hi Guys, I have faced an issue : 

`Xamarin.UITest.XDB.Exceptions.DeviceAgentException : Failed to launch DeviceAgent
ExitCode: 64
xcodebuild: error: option 'Destination' requires at least one parameter of the form 'key=value'
Stack trace:
   at Xamarin.UITest.iOS.iOSAppLauncher.LaunchAppLocal(IiOSAppConfiguration appConfiguration, HttpClient httpClient, Boolean clearAppData)
   at Xamarin.UITest.iOS.iOSAppLauncher.LaunchApp(IiOSAppConfiguration appConfiguration, HttpClient httpClient, TestCloudiOSAppConfiguration testCloudAppConfiguration, HttpClient testCloudWsClient, HttpClient xtcServicesClient, Boolean testCloudUseDeviceAgent)
   at Xamarin.UITest.iOS.iOSApp..ctor(IiOSAppConfiguration appConfiguration, IExecutor executor)
   at Xamarin.UITest.iOS.iOSApp..ctor(IiOSAppConfiguration appConfiguration)
   at Xamarin.UITest.Configuration.iOSAppConfigurator.StartApp(AppDataMode appDataMode)
   at TEstCore.Tests.Test3() in /Users/ymatviienko/Projects/TEstCore/TEstCore/UnitTest1.cs:line 29`

With such configuration: 
NUnit 3.12.0 
Xamarin.UITest 3.0.5(same issue with 3.0.6. dev)
 iOS 13.3 simulator
 XCode 11.3 
.netcore 3.0
When I have the same configuration but with NET framework 7.7.2, all works well.
Does Xamarin.UITest support .netcore 3.0?

**Comment by derpixeldan** [comment]
@imatviienkoomcinc please reach out via support (blue circle button in the lower right of App Center) so we can better investigate the problem.

**Comment by MihaMarkic** [comment]
Sadly, the answer is no - it doesn't support .NET Core or 5.
