### ISSUE TITLE
My android build is failing while running yarn install in app centre

### ISSUE THREAD

**Issue by amitmundrag08** [microsoft/appcenter#2028]
I would like to know any solution or the reason why suddenly it started to fail. It was working fine for me yesterday.

My machine details :- 
Agent machine name: 'Mac-1603948233974'
Current agent version: '2.175.2'
##[group]Operating System
Mac OS X
10.15.7

Any fix which can be done from our side? We are using detox library version :- 14.5.1

The error I am facing :- 

Extracting Detox sources...
Building Detox.framework from /Users/runner/work/1/s/mobile/node_modules/detox/ios_src...
child_process.js:630
    throw err;

Error: Command failed: /Users/runner/work/1/s/mobile/node_modules/detox/scripts/build_framework.ios.sh
    at checkExecSyncError (child_process.js:607:13)
    at Object.execFileSync (child_process.js:627:13)
    at Object.<anonymous> (/Users/runner/work/1/s/mobile/node_modules/detox/scripts/postinstall.js:2:27)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)

**Comment by diegodelvalle** [comment]
Having the same issue here with version 12.5.0
