### ISSUE TITLE
App Center Android app crashes after download of our app

### ISSUE THREAD

**Issue by tobi512** [microsoft/appcenter#2100]
Hi there, 
not sure if this is the right place to submit, but since you "disabled" the bug issue template by redirecting to appcenter.ms, I'll just leave this here as a feature request. **This is definitely a bug!**

When using the App Center app on Android, I often get crashes after the download of an app version is complete. See the following log in Logcat, looks like a problem on your side:

```
2021-01-22 11:14:46.451 10192-10192/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.microsoft.hockeyapp.testerapp, PID: 10192
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2340692 bytes
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:160)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: android.os.TransactionTooLargeException: data parcel size 2340692 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1145)
        at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:3891)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:144)
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.
```

Our app currently has a download size of ~70 MB if that helps in by any means. Using the latest version of App Center (2.1.2).

Due to this issue, I'm currently unable to use App Center in 90% of cases, after the download completes, I'm stuck on the app version overview page again without the installation dialog, so please fix this!

Cheers, 
Tobias

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us!
We already fixed this issue and a fix will be released soon.
Also, could you please open issues related to App Center App on the intercom. Please see how to open the intercom ticket [here](https://docs.microsoft.com/en-us/appcenter/help).

**Comment by tobi512** [comment]
Hey @AnastasiaKubova,
any infos on the eta of the fix? One week later and still no update available, a small bugfix release would be much appreciated, thanks!

**Comment by MatkovIvan** [comment]
Hi @tobi512,
No specific ETA, but it's on our backlog. We'll release fixed version soon. Thanks.
