### ISSUE TITLE
Build fail React Native 0.68.2

### ISSUE THREAD

**Issue by eldanielsoares** [microsoft/appcenter#2443]
Since I updated React native to version 0.68+ I can no longer build my app.
Now whenever I try I get this error: 

`SYSTEMVSSCONNECTION exists true
[command]/Users/runner/work/1/s/android/gradlew -DAPPCENTER_KEYSTORE_PASSWORD=*** -DMOBILECENTER_KEYSTORE_PASSWORD=*** -DAPPCENTER_KEYSTORE_FILE_ID=***.keystore -DMOBILECENTER_KEYSTORE_FILE_ID=***.keystore -DAPPCENTER_KEY_ALIAS=*** -DMOBILECENTER_KEY_ALIAS=*** -DAPPCENTER_KEY_PASSWORD=*** -DMOBILECENTER_KEY_PASSWORD=*** -p android clean :app:assembleRelease :app:bundleRelease
/Users/runner/work/1/s/android/gradlew: line 195: unexpected EOF while looking for matching `"'
/Users/runner/work/1/s/android/gradlew: line 196: syntax error: unexpected end of file
Error: /Users/runner/work/1/s/android/gradlew failed with return code: 2
    at ChildProcess.<anonymous> (/Users/runner/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/1.128.0/node_modules/vsts-task-lib/toolrunner.js:569:30)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:509:12)
##[error]Error: /Users/runner/work/1/s/android/gradlew failed with return code: 2`

**Comment by joaoeliandro** [comment]
Same error here, any news?
