### ISSUE TITLE
Cannot build iOS React Native project

### ISSUE THREAD

**Issue by telmen** [microsoft/appcenter#2462]
**Describe the solution you'd like**
Should be able to build iOS successfully

**Additional context**

Facing an error when I try to build iOS of React Native project. 

the error log:
```txt
...
failed to read project: React {
  error: Error: ENOENT: no such file or directory, open '/Users/runner/work/1/s/node_modules/react-native/React/React.xcodeproj/project.pbxproj'
      at Object.openSync (node:fs:594:3)
      at Object.readFileSync (node:fs:462:35)
      at XcodeBuildsSettingsUpdater.<anonymous> (/Users/runner/runners/2.209.0/scripts/build-xcproject-analyzer/node_modules/@build/xcproject-analyzer-script/script/xcode-builds-settings-updater.js:58:45)
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/runners/2.209.0/scripts/build-xcproject-analyzer/node_modules/@build/xcproject-analyzer-script/script/xcode-builds-settings-updater.js:4:58)
      at tryCatcher (/Users/runner/runners/2.209.0/scripts/build-xcproject-analyzer/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/runner/runners/2.209.0/scripts/build-xcproject-analyzer/node_modules/bluebird/js/release/promise.js:517:31)
      at Promise._settlePromise (/Users/runner/runners/2.209.0/scripts/build-xcproject-analyzer/node_modules/bluebird/js/release/promise.js:574:18)
      at Promise._settlePromise0 (/Users/runner/runners/2.209.0/scripts/build-xcproject-analyzer/node_modules/bluebird/js/release/promise.js:619:10)
      at Promise._settlePromises (/Users/runner/runners/2.209.0/scripts/build-xcproject-analyzer/node_modules/bluebird/js/release/promise.js:699:18)
      at _drainQueueStep (/Users/runner/runners/2.209.0/scripts/build-xcproject-analyzer/node_modules/bluebird/js/release/async.js:138:12)
      at _drainQueue (/Users/runner/runners/2.209.0/scripts/build-xcproject-analyzer/node_modules/bluebird/js/release/async.js:131:9)
      at Async._drainQueues (/Users/runner/runners/2.209.0/scripts/build-xcproject-analyzer/node_modules/bluebird/js/release/async.js:147:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/runner/runners/2.209.0/scripts/build-xcproject-analyzer/node_modules/bluebird/js/release/async.js:17:14)
      at processImmediate (node:internal/timers:466:21) {
    errno: -2,
    syscall: 'open',
    code: 'ENOENT',
    path: '/Users/runner/work/1/s/node_modules/react-native/React/React.xcodeproj/project.pbxproj'
  }
}
...
```

**Comment by maoapp** [comment]
still happening here
<img width="838" alt="image" src="https://user-images.githubusercontent.com/19539930/192458488-39395042-b912-43b6-8a15-940a6f44e9f5.png">

**Comment by maoapp** [comment]
were you able to fix it @telmen ?
