### ISSUE TITLE
"Pod install" phase should run `bundle exec pod install` instead of `pod install`

### ISSUE THREAD

**Issue by Adnan-Bacic** [microsoft/appcenter#2540]
**Describe the solution you'd like**

running `pod install` doesnt necessarily run the projects version of CocoaPods. my react-native app is currently at version 0.70.8, which uses CocoaPods version 1.11.3. i can verify this at the bottom of the `Podfile.lock` file where it says `COCOAPODS: 1.11.3`.

i can see that appcenter uses another version of CocoaPods. i can see in the logs that is runs version 1.12.0 of CocoaPods when running `pod install`:

```
2023-04-13T05:52:30.6545900Z ➤ YN0000: │ projectName@workspace:. STDERR npm WARN exec The following package was not found and will be installed: pod-install
2023-04-13T05:52:30.9368590Z ➤ YN0000: │ projectName@workspace:. STDOUT Scanning for pods...
2023-04-13T05:52:36.0880980Z ➤ YN0000: │ projectName@workspace:. STDOUT 1.12.0
2023-04-13T05:52:36.0953920Z ➤ YN0000: │ projectName@workspace:. STDOUT > pod install
```

according to the cocoapods docs:

https://guides.cocoapods.org/using/a-gemfile.html#using-cocoapods-with-a-gemfile

> With a Gemfile setup, you run bundle install to install, or bundle update to update within your Gemfile's constraints. From here on in however, you will need to remember to run bundle exec before any terminal commands that have come in via bundler. Given that CocoaPods is included in the above this means any time you would write pod XX YY you need to do bundle exec pod XX YY.
> Doing it without bundle exec will bypass your Gemfile's specific versioning and will use the latest version of the library within RubyGems. This could potentially be the exact same version, but it can often not.

the `Gemfile` was added in react-native 0.67.0, as seen here:

https://react-native-community.github.io/upgrade-helper/?from=0.66.5&to=0.67.0

so locally on my computer, ive started to run `bundle exec pod install` instead of `pod install`. and i want to force appcenter to do that too.

i tried using a postinstall script with the following:

`cd ios && bundle exec pod install --clean-install`

this causes to CI to fail. i can see it actually uses to correct version of CocoaPods at least. here are some logs:

android:

```
2023-04-13T06:20:54.9799000Z ➤ YN0000: │ projectName@workspace:. STDERR bundler: failed to load command: pod (/usr/local/lib/ruby/gems/2.7.0/bin/pod)
2023-04-13T06:20:54.9804080Z ➤ YN0000: │ projectName@workspace:. STDERR /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.4.11/lib/bundler/definition.rb:524:in `materialize': Could not find cocoapods-1.11.3, addressable-2.8.0, claide-1.1.0, cocoapods-core-1.11.3, cocoapods-deintegrate-1.0.5, cocoapods-downloader-1.6.3, cocoapods-plugins-1.0.0, cocoapods-search-1.0.1, cocoapods-trunk-1.6.0, cocoapods-try-1.2.0, colored2-3.1.2, escape-0.0.4, fourflusher-2.3.1, gh_inspector-1.1.3, molinillo-0.8.0, nap-1.1.0, ruby-macho-2.5.1, xcodeproj-1.21.0, public_suffix-4.0.7, activesupport-6.1.5, algoliasearch-1.27.5, concurrent-ruby-1.1.10, fuzzy_match-2.0.4, netrc-0.11.0, typhoeus-1.4.0, CFPropertyList-3.0.5, atomos-0.1.3, nanaimo-0.3.0, rexml-3.2.5, i18n-1.10.0, minitest-5.15.0, tzinfo-2.0.4, zeitwerk-2.5.4, httpclient-2.8.3, json-2.6.1, ethon-0.15.0, ffi-1.15.5 in locally installed gems (Bundler::GemNotFound)
2023-04-13T06:20:54.9808700Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.4.11/lib/bundler/definition.rb:197:in `specs'
2023-04-13T06:20:54.9810790Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.4.11/lib/bundler/definition.rb:254:in `specs_for'
2023-04-13T06:20:54.9812810Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.4.11/lib/bundler/runtime.rb:18:in `setup'
2023-04-13T06:20:54.9814720Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.4.11/lib/bundler.rb:171:in `setup'
2023-04-13T06:20:54.9817610Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.4.11/lib/bundler/setup.rb:23:in `block in <top (required)>'
2023-04-13T06:20:54.9819680Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.4.11/lib/bundler/ui/shell.rb:159:in `with_level'
2023-04-13T06:20:54.9821510Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.4.11/lib/bundler/ui/shell.rb:111:in `silence'
2023-04-13T06:20:54.9824430Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.4.11/lib/bundler/setup.rb:23:in `<top (required)>'
2023-04-13T06:20:54.9827080Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.4.11/lib/bundler/cli/exec.rb:56:in `require_relative'
2023-04-13T06:20:54.9831460Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.4.11/lib/bundler/cli/exec.rb:56:in `kernel_load'
2023-04-13T06:20:54.9844750Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.4.11/lib/bundler/cli/exec.rb:23:in `run'
2023-04-13T06:20:54.9848440Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.4.11/lib/bundler/cli.rb:492:in `exec'
2023-04-13T06:20:54.9850410Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.4.11/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
2023-04-13T06:20:54.9852370Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.4.11/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
2023-04-13T06:20:54.9854530Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.4.11/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
2023-04-13T06:20:54.9856450Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.4.11/lib/bundler/cli.rb:34:in `dispatch'
2023-04-13T06:20:54.9858220Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.4.11/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
2023-04-13T06:20:54.9860290Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.4.11/lib/bundler/cli.rb:28:in `start'
2023-04-13T06:20:54.9862370Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.4.11/exe/bundle:45:in `block in <top (required)>'
2023-04-13T06:20:54.9863880Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.4.11/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
2023-04-13T06:20:54.9866050Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.4.11/exe/bundle:33:in `<top (required)>'
2023-04-13T06:20:54.9867970Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/2.7.0/bin/bundle:25:in `load'
2023-04-13T06:20:54.9869500Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/2.7.0/bin/bundle:25:in `<main>'
2023-04-13T06:20:55.0044190Z ➤ YN0009: │ projectName@workspace:. couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/xfs-e3c99198/build.log)
2023-04-13T06:20:55.0048010Z ➤ YN0000: └ Completed in 32s 150ms
2023-04-13T06:20:55.1419930Z ➤ YN0000: Failed with errors in 1m 42s
2023-04-13T06:20:55.7496940Z ##[error]/bin/sh failed with return code: 1
2023-04-13T06:20:55.7927780Z ##[error]/bin/sh failed with error: /bin/sh failed with return code: 1
2023-04-13T06:20:55.7954360Z ##[section]Finishing: yarn/npm install
```

ios:

```
2023-04-13T06:19:26.7564610Z ➤ YN0000: │ projectName@workspace:. STDERR bundler: failed to load command: pod (/usr/local/lib/ruby/gems/3.0.0/bin/pod)
2023-04-13T06:19:26.7577760Z ➤ YN0000: │ projectName@workspace:. STDERR /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/definition.rb:524:in `materialize': Could not find cocoapods-1.11.3, addressable-2.8.0, claide-1.1.0, cocoapods-core-1.11.3, cocoapods-deintegrate-1.0.5, cocoapods-downloader-1.6.3, cocoapods-plugins-1.0.0, cocoapods-search-1.0.1, cocoapods-trunk-1.6.0, cocoapods-try-1.2.0, colored2-3.1.2, escape-0.0.4, fourflusher-2.3.1, gh_inspector-1.1.3, molinillo-0.8.0, nap-1.1.0, ruby-macho-2.5.1, xcodeproj-1.21.0, public_suffix-4.0.7, activesupport-6.1.5, algoliasearch-1.27.5, concurrent-ruby-1.1.10, fuzzy_match-2.0.4, netrc-0.11.0, typhoeus-1.4.0, CFPropertyList-3.0.5, atomos-0.1.3, nanaimo-0.3.0, rexml-3.2.5, i18n-1.10.0, minitest-5.15.0, tzinfo-2.0.4, zeitwerk-2.5.4, httpclient-2.8.3, json-2.6.1, ethon-0.15.0, ffi-1.15.5 in locally installed gems (Bundler::GemNotFound)
2023-04-13T06:19:26.7581820Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/definition.rb:197:in `specs'
2023-04-13T06:19:26.7583850Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/definition.rb:254:in `specs_for'
2023-04-13T06:19:26.7585490Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/runtime.rb:18:in `setup'
2023-04-13T06:19:26.7586990Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.4.10/lib/bundler.rb:171:in `setup'
2023-04-13T06:19:26.7588530Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/setup.rb:23:in `block in <top (required)>'
2023-04-13T06:19:26.7590350Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/ui/shell.rb:159:in `with_level'
2023-04-13T06:19:26.7592540Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/ui/shell.rb:111:in `silence'
2023-04-13T06:19:26.7594470Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/setup.rb:23:in `<top (required)>'
2023-04-13T06:19:26.7598650Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:56:in `require_relative'
2023-04-13T06:19:26.7605390Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:56:in `kernel_load'
2023-04-13T06:19:26.7607070Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:23:in `run'
2023-04-13T06:19:26.7609520Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/cli.rb:492:in `exec'
2023-04-13T06:19:26.7611370Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
2023-04-13T06:19:26.7613640Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
2023-04-13T06:19:26.7615630Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
2023-04-13T06:19:26.7617210Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/cli.rb:34:in `dispatch'
2023-04-13T06:19:26.7619120Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
2023-04-13T06:19:26.7620290Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/cli.rb:28:in `start'
2023-04-13T06:19:26.7621530Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.4.10/exe/bundle:45:in `block in <top (required)>'
2023-04-13T06:19:26.7623420Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
2023-04-13T06:19:26.7625060Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.4.10/exe/bundle:33:in `<top (required)>'
2023-04-13T06:19:26.7626480Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/3.0.0/bin/bundle:25:in `load'
2023-04-13T06:19:26.7628010Z ➤ YN0000: │ projectName@workspace:. STDERR 	from /usr/local/lib/ruby/gems/3.0.0/bin/bundle:25:in `<main>'
2023-04-13T06:19:26.7800690Z ➤ YN0009: │ projectName@workspace:. couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/xfs-0862854a/build.log)
2023-04-13T06:19:26.7802240Z ➤ YN0000: └ Completed in 31s 443ms
2023-04-13T06:19:26.9172270Z ➤ YN0000: Failed with errors in 1m 28s
2023-04-13T06:19:27.4882580Z ##[error]/bin/sh failed with return code: 1
2023-04-13T06:19:27.4896740Z ##[error]/bin/sh failed with error: /bin/sh failed with return code: 1
2023-04-13T06:19:27.4903770Z ##[section]Finishing: yarn/npm install
```

CocoaPods is only relevant for ios, but the command also fails for android.

im also not sure why, but i noticed it used different versions of gems and bundler for android and ios.

android:
`/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.4.11/`

ios:
`/usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.4.10`

i have not tried it, but this may be solved by adding a `.ruby-version` file in my project. (this file was added in 0.70.0 - https://react-native-community.github.io/upgrade-helper/?from=0.69.9&to=0.70.0 but removed again in 0.70.8 - https://react-native-community.github.io/upgrade-helper/?from=0.70.7&to=0.70.8). i may add this file again regardless though.

it was added again in 0.71.0:
https://react-native-community.github.io/upgrade-helper/?from=0.70.8&to=0.71.0

and then removed again in 0.71.5:
https://react-native-community.github.io/upgrade-helper/?from=0.71.4&to=0.71.5

notice that it now at least uses version 1.11.3 of CocoaPods, as desired.

**Describe alternatives you've considered**

**Additional context**

**Comment by MikhailSuendukov** [comment]
Hello @Adnan-Bacic , I'm sorry, but I unfortunately did not quite understand the question. Do you suggest in the documentation to mention bundle exec pod install instead of pod install?

**Comment by Adnan-Bacic** [comment]
im sorry if i wasent clear.

the problem i have is that if i set `bundle exec pod install` as a postinstall script, then the CI fails. only plain `pod install` works. however i want to force the correct CocoaPods version that i have in my project, this requires `bundle exec pod install` to run.

**Comment by Adnan-Bacic** [comment]
i will try to look into this. though i dont think its the ideal solution. it still requires you to hardcode the versions in the file. alternatively, it may be possible to extract the version from the `Gemfile` to avoid hardcoding.

i think the ideal solution would be that appcenter runs `bundle exec pod install` instead of `pod install` by default in the "Pod install" phase. i think most people will not notice that appcenter may use a newer version of CocoaPods, so most would never add this script.

also simply running `bundle exec pod install` will avoid the need for a custom script, as the standard solution would just be used.

**Comment by Adnan-Bacic** [comment]
i changed this issue slightly since i created it.

at first i was using a `postinstall` script and i wanted to use that to run `bundle exec pod install`.

however appcenter has its own phase to install pods, and i changed the issue to focus on that phase. i believe that would be the correct place to change it.

**Comment by Adnan-Bacic** [comment]
i found this other script inside the same folder which was posted above:
https://github.com/microsoft/appcenter/blob/master/sample-build-scripts/react-native/compare-cocoapods/appcenter-post-clone.sh

i think this one is better. it automatically find the CocoaPods version from the `Podfile.lock` file.

**Comment by Adnan-Bacic** [comment]
i tried this script: https://github.com/microsoft/appcenter/blob/master/sample-build-scripts/react-native/compare-cocoapods/appcenter-post-clone.sh

and its still not working correctly.

my post-clone script does install the correct version of CocoaPods:

`2023-04-26T07:49:53.2105230Z Successfully installed cocoapods-1.11.3`

but it is not being used in the "Pod install" phase:

```
2023-04-26T07:55:52.1201670Z [command]/usr/local/lib/ruby/gems/3.0.0/bin/pod --version
2023-04-26T07:55:53.7324350Z 1.12.0
2023-04-26T07:55:53.9196410Z [command]/usr/local/lib/ruby/gems/3.0.0/bin/pod install --repo-update
```

**Comment by DmitriyKirakosyan** [comment]
@Adnan-Bacic thank you for the details! I shared the information with the proper team and they will update you once they have time to take a look.

Meanwhile I recommend you to reach out to [our support team](https://learn.microsoft.com/en-us/appcenter/help), they will help you resolve the issue asap.

**Comment by stephan-markovic** [comment]
@Adnan-Bacic 
If I understand the problem correctly, adding appcenter-post-clone.sh with the following should suffice.

#!/usr/bin/env bash
CUSTOM_COCOAPODS_VERSION=\`grep COCOAPODS Podfile.lock | sed 's/.*[[:space:]]//'`
gem uninstall cocoapods -aIx
gem install cocoapods -v $CUSTOM_COCOAPODS_VERSION

**Comment by Adnan-Bacic** [comment]
> @Adnan-Bacic If I understand the problem correctly, adding appcenter-post-clone.sh with the following should suffice.
> 
> #!/usr/bin/env bash CUSTOM_COCOAPODS_VERSION=`grep COCOAPODS Podfile.lock | sed 's/.*[[:space:]]//'` gem uninstall cocoapods -aIx gem install cocoapods -v $CUSTOM_COCOAPODS_VERSION

this script looks slighlty different than the one i posted above, but overall the same.

https://github.com/microsoft/appcenter/issues/2540#issuecomment-1523023744

you can see that appcenter fails to uninstall the installed versions of cocoapods.

**Comment by stephan-markovic** [comment]
@Adnan-Bacic 
![image](https://github.com/microsoft/appcenter/assets/100690922/7ef7ba68-fac6-4669-86ad-9b1c40339574)

**Comment by Adnan-Bacic** [comment]
ok i got it to work. i think the difference is due to the arguments passed to the uninstall script

`gem uninstall cocoapods --all --executables` - fails

`gem uninstall cocoapods -aIx` - works

for reference, this is my current appcenter-post-clone.sh script:

```
CURRENT_COCOAPODS_VERSION=`sed -n -e 's/^COCOAPODS: \([0-9.]*\)/\1/p' ios/Podfile.lock`
ENV_COCOAPODS_VERSION=`pod --version`

# check if not the same version, reinstall cocoapods version to current project's
if [ $CURRENT_COCOAPODS_VERSION != $ENV_COCOAPODS_VERSION ];
then
    echo "Uninstalling all CocoaPods versions"
    gem uninstall cocoapods -aIx
    echo "Installing CocoaPods version $CURRENT_COCOAPODS_VERSION"
    gem install cocoapods -v $CURRENT_COCOAPODS_VERSION
else 
    echo "CocoaPods version is suitable for the project"
fi;
```

it is basically the script in the previous link, with the updated uninstall command @stephan-markovic posted.
