### ISSUE TITLE
Xamarin.UItest crashes when running the suite that has 35+ tests on .NET 6.0 and above

### ISSUE THREAD

**Issue by Moshex** [microsoft/appcenter#2644]
I have an issue with my test suite that has over 100 tests, when doing a full test run on ios, Xamarin UItest will crash. This issue generally occurs at the 35th test but can happen before or after. I will post the error that occurs when the crash happens. Any help with fixing this issue is greatly appreciated whether it be in code or in Mac environment. Keep in mind that I do not see this issue on .NET framework 4.8. I am on Xamarin.UITest version 4.4.0 running the test on an iPhone simulator with os version 17.2.

```
Exit code is 134 (username
Process terminated. A callback was made on a garbage collected delegate of type 'Xamarin.UITest.Shared!Xamarin.UITest.Shared.iOS.Queries.QueryConnectediOSDevices+DeviceNotificationDelegate::Invoke'.
Repeat 2 times:
--------------------------------
   at Xamarin.UITest.Shared.iOS.Queries.QueryConnectediOSDevices+NativeMethods.AMDeviceNotificationUnsubscribe(IntPtr)
--------------------------------
   at Xamarin.UITest.Shared.iOS.Queries.QueryConnectediOSDevices+DeviceFinder.GetConnectedDevices(System.String)
   at Xamarin.UITest.Shared.iOS.Queries.QueryConnectediOSDevices.Execute()
   at Xamarin.UITest.iOS.iOSAppLauncher.GetOrValidateSimId(Xamarin.UITest.iOS.Instruments, System.String)
   at Xamarin.UITest.iOS.iOSAppLauncher.LaunchAppLocal(Xamarin.UITest.Configuration.IiOSAppConfiguration, Xamarin.UITest.Shared.Http.HttpClient, Boolean)
   at Xamarin.UITest.iOS.iOSAppLauncher.LaunchApp(Xamarin.UITest.Configuration.IiOSAppConfiguration, Xamarin.UITest.Shared.Http.HttpClient, Xamarin.UITest.TestCloud.TestCloudiOSAppConfiguration, Xamarin.UITest.Shared.Http.HttpClient, Xamarin.UITest.Shared.Http.HttpClient, Boolean)
   at Xamarin.UITest.iOS.iOSApp..ctor(Xamarin.UITest.Configuration.IiOSAppConfiguration, Xamarin.UITest.Shared.Execution.IExecutor)
   at Xamarin.UITest.iOS.iOSApp..ctor(Xamarin.UITest.Configuration.IiOSAppConfiguration)
   at Xamarin.UITest.Configuration.iOSAppConfigurator.StartApp(Xamarin.UITest.Configuration.AppDataMode)
   at WellRx.UITests.AppInitializer.IosStartApp(System.String, Xamarin.UITest.Configuration.AppDataMode)
   at WellRx.UITests.AppInitializer.StartApp(Xamarin.UITest.Platform, System.String, Boolean)
   at WellRx.UITests.Features.FeatureBase.BeforeEachTest()
   at DynamicClass.InvokeStub_FeatureBase.BeforeEachTest(System.Object, System.Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(System.Object, System.Reflection.BindingFlags)
   at NUnit.Framework.Internal.Reflect.InvokeMethod(System.Reflection.MethodInfo, System.Object, System.Object[])
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUp(NUnit.Framework.Internal.TestExecutionContext)
   at NUnit.Framework.Internal.Commands.DelegatingTestCommand.RunTestMethodInThreadAbortSafeZone(NUnit.Framework.Internal.TestExecutionContext, System.Action)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.Execute(NUnit.Framework.Internal.TestExecutionContext)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem+<>c__DisplayClass3_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils+<>c__DisplayClass1_0`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<DoIsolated>b__0(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated(System.Threading.ContextCallback, System.Object)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Func`1<System.__Canon>)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
   at NUnit.Framework.Internal.Execution.WorkItem.RunOnCurrentThread()
   at NUnit.Framework.Internal.Execution.WorkItem.Execute()
   at NUnit.Framework.Internal.Execution.ParallelWorkItemDispatcher.Dispatch(NUnit.Framework.Internal.Execution.WorkItem, NUnit.Framework.Internal.Execution.ParallelExecutionStrategy)
   at NUnit.Framework.Internal.Execution.ParallelWorkItemDispatcher.Dispatch(NUnit.Framework.Internal.Execution.WorkItem)
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.RunChildren()
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork()
   at NUnit.Framework.Internal.Execution.WorkItem.RunOnCurrentThread()
   at NUnit.Framework.Internal.Execution.WorkItem.Execute()
   at NUnit.Framework.Internal.Execution.TestWorker.TestWorkerThreadProc()
   at System.Threading.Thread.StartCallback())

Last runner error: Process /usr/local/share/dotnet/dotnet:49485 exited with code '134'. mmoadeb Process terminated. A callback was made on a garbage collected delegate of type 'Xamarin.UITest.Shared!Xamarin.UITest.Shared.iOS.Queries.QueryConnectediOSDevices+DeviceNotificationDelegate::Invoke'. Repeat 2 times: -------------------------------- at Xamarin.UITest.Shared.iOS.Queries.QueryConnectediOSDevices+NativeMethods.AMDeviceNotificationUnsubscribe(IntPtr) -------------------------------- at Xamarin.UITest.Shared.iOS.Queries.QueryConnectediOSDevices+DeviceFinder.GetConnectedDevices(System.String) at Xamarin.UITest.Shared.iOS.Queries.QueryConnectediOSDevices.Execute() at Xamarin.UITest.iOS.iOSAppLauncher.GetOrValidateSimId(Xamarin.UITest.iOS.Instruments, System.String) at Xamarin.UITest.iOS.iOSAppLauncher.LaunchAppLocal(Xamarin.UITest.Configuration.IiOSAppConfiguration, Xamarin.UITest.Shared.Http.HttpClient, Boolean) at Xamarin.UITest.iOS.iOSAppLauncher.LaunchApp(Xamarin.UITest.Configuration.IiOSAppConfiguration, Xamarin.UITest.Shared.Http.HttpClient, Xamarin.UITest.TestCloud.TestCloudiOSAppConfiguration, Xamarin.UITest.Shared.Http.HttpClient, Xamarin.UITest.Shared.Http.HttpClient, Boolean) at Xamarin.UITest.iOS.iOSApp..ctor(Xamarin.UITest.Configuration.IiOSAppConfiguration, Xamarin.UITest.Shared.Execution.IExecutor) at Xamarin.UITest.iOS.iOSApp..ctor(Xamarin.UITest.Configuration.IiOSAppConfiguration) at Xamarin.UITest.Configuration.iOSAppConfigurator.StartApp(Xamarin.UITest.Configuration.AppDataMode) at WellRx.UITests.AppInitializer.IosStartApp(System.String, Xamarin.UITest.Configuration.AppDataMode) at WellRx.UITests.AppInitializer.StartApp(Xamarin.UITest.Platform, System.String, Boolean) at WellRx.UITests.Features.FeatureBase.BeforeEachTest() at DynamicClass.InvokeStub_FeatureBase.BeforeEachTest(System.Object, System.Object, IntPtr*) at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(System.Object, System.Reflection.BindingFlags) at NUnit.Framework.Internal.Reflect.InvokeMethod(System.Reflection.MethodInfo, System.Object, System.Object[]) at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUp(NUnit.Framework.Internal.TestExecutionContext) at NUnit.Framework.Internal.Commands.DelegatingTestCommand.RunTestMethodInThreadAbortSafeZone(NUnit.Framework.Internal.TestExecutionContext, System.Action) at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.Execute(NUnit.Framework.Internal.TestExecutionContext) at NUnit.Framework.Internal.Execution.SimpleWorkItem+<>c__DisplayClass3_0.<PerformWork>b__0() at NUnit.Framework.Internal.ContextUtils+<>c__DisplayClass1_0`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<DoIsolated>b__0(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at NUnit.Framework.Internal.ContextUtils.DoIsolated(System.Threading.ContextCallback, System.Object) at NUnit.Framework.Internal.ContextUtils.DoIsolated[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Func`1<System.__Canon>) at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork() at NUnit.Framework.Internal.Execution.WorkItem.RunOnCurrentThread() at NUnit.Framework.Internal.Execution.WorkItem.Execute() at NUnit.Framework.Internal.Execution.ParallelWorkItemDispatcher.Dispatch(NUnit.Framework.Internal.Execution.WorkItem, NUnit.Framework.Internal.Execution.ParallelExecutionStrategy) at NUnit.Framework.Internal.Execution.ParallelWorkItemDispatcher.Dispatch(NUnit.Framework.Internal.Execution.WorkItem) at NUnit.Framework.Internal.Execution.CompositeWorkItem.RunChildren() at NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork() at NUnit.Framework.Internal.Execution.WorkItem.RunOnCurrentThread() at NUnit.Framework.Internal.Execution.WorkItem.Execute() at NUnit.Framework.Internal.Execution.TestWorker.TestWorkerThreadProc() at System.Threading.Thread.StartCallback()

--- EXCEPTION #1/1 [LoggerException]
Message = “
  Process /usr/local/share/dotnet/dotnet:49485 exited with code '134'.
  mmoadeb
  Process terminated. A callback was made on a garbage collected delegate of type 'Xamarin.UITest.Shared!Xamarin.UITest.Shared.iOS.Queries.QueryConnectediOSDevices+DeviceNotificationDelegate::Invoke'.
  Repeat 2 times:
  --------------------------------
     at Xamarin.UITest.Shared.iOS.Queries.QueryConnectediOSDevices+NativeMethods.AMDeviceNotificationUnsubscribe(IntPtr)
  --------------------------------
     at Xamarin.UITest.Shared.iOS.Queries.QueryConnectediOSDevices+DeviceFinder.GetConnectedDevices(System.String)
     at Xamarin.UITest.Shared.iOS.Queries.QueryConnectediOSDevices.Execute()
     at Xamarin.UITest.iOS.iOSAppLauncher.GetOrValidateSimId(Xamarin.UITest.iOS.Instruments, System.String)
     at Xamarin.UITest.iOS.iOSAppLauncher.LaunchAppLocal(Xamarin.UITest.Configuration.IiOSAppConfiguration, Xamarin.UITest.Shared.Http.HttpClient, Boolean)
     at Xamarin.UITest.iOS.iOSAppLauncher.LaunchApp(Xamarin.UITest.Configuration.IiOSAppConfiguration, Xamarin.UITest.Shared.Http.HttpClient, Xamarin.UITest.TestCloud.TestCloudiOSAppConfiguration, Xamarin.UITest.Shared.Http.HttpClient, Xamarin.UITest.Shared.Http.HttpClient, Boolean)
     at Xamarin.UITest.iOS.iOSApp..ctor(Xamarin.UITest.Configuration.IiOSAppConfiguration, Xamarin.UITest.Shared.Execution.IExecutor)
     at Xamarin.UITest.iOS.iOSApp..ctor(Xamarin.UITest.Configuration.IiOSAppConfiguration)
     at Xamarin.UITest.Configuration.iOSAppConfigurator.StartApp(Xamarin.UITest.Configuration.AppDataMode)
     at WellRx.UITests.AppInitializer.IosStartApp(System.String, Xamarin.UITest.Configuration.AppDataMode)
     at WellRx.UITests.AppInitializer.StartApp(Xamarin.UITest.Platform, System.String, Boolean)
     at WellRx.UITests.Features.FeatureBase.BeforeEachTest()
     at DynamicClass.InvokeStub_FeatureBase.BeforeEachTest(System.Object, System.Object, IntPtr*)
     at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(System.Object, System.Reflection.BindingFlags)
     at NUnit.Framework.Internal.Reflect.InvokeMethod(System.Reflection.MethodInfo, System.Object, System.Object[])
     at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUp(NUnit.Framework.Internal.TestExecutionContext)
     at NUnit.Framework.Internal.Commands.DelegatingTestCommand.RunTestMethodInThreadAbortSafeZone(NUnit.Framework.Internal.TestExecutionContext, System.Action)
     at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.Execute(NUnit.Framework.Internal.TestExecutionContext)
     at NUnit.Framework.Internal.Execution.SimpleWorkItem+<>c__DisplayClass3_0.<PerformWork>b__0()
     at NUnit.Framework.Internal.ContextUtils+<>c__DisplayClass1_0`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<DoIsolated>b__0(System.Object)
     at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
     at NUnit.Framework.Internal.ContextUtils.DoIsolated(System.Threading.ContextCallback, System.Object)
     at NUnit.Framework.Internal.ContextUtils.DoIsolated[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Func`1<System.__Canon>)
     at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
     at NUnit.Framework.Internal.Execution.WorkItem.RunOnCurrentThread()
     at NUnit.Framework.Internal.Execution.WorkItem.Execute()
     at NUnit.Framework.Internal.Execution.ParallelWorkItemDispatcher.Dispatch(NUnit.Framework.Internal.Execution.WorkItem, NUnit.Framework.Internal.Execution.ParallelExecutionStrategy)
     at NUnit.Framework.Internal.Execution.ParallelWorkItemDispatcher.Dispatch(NUnit.Framework.Internal.Execution.WorkItem)
     at NUnit.Framework.Internal.Execution.CompositeWorkItem.RunChildren()
     at NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork()
     at NUnit.Framework.Internal.Execution.WorkItem.RunOnCurrentThread()
     at NUnit.Framework.Internal.Execution.WorkItem.Execute()
     at NUnit.Framework.Internal.Execution.TestWorker.TestWorkerThreadProc()
     at System.Threading.Thread.StartCallback()
”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  at JetBrains.Util.ILoggerEx.LogMessage(ILogger this, LoggingLevel level, String message) in LogMessage.il:line IL_002E mvid 6B9F
     at JetBrains.Util.ILoggerEx.Error(ILogger this, String message) in Error.il:line IL_0000 mvid 6B9F
     at JetBrains.ReSharper.UnitTestFramework.Execution.TestRunner.TestRunnerRunStrategy.AnalyseProcessCrash(ProcessExitedUnexpectedlyException ex, IUnitTestRun run) in AnalyseProcessCrash.il:line IL_006B mvid 4F79
     at JetBrains.ReSharper.UnitTestFramework.Execution.TestRunner.TestRunnerRunStrategy.Run(IUnitTestRun run) in Run.il:line IL_01C8 mvid 4F79
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s) in ExecutionContextCallback.il:line IL_0000 mvid 999C
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in RunInternal.il:line IL_0040 mvid 999C
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in MoveNext.il:line IL_0000 mvid 999C or MoveNext.il:line IL_0040 mvid 999C
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in MoveNext.il:line IL_0000 mvid 999C or MoveNext.il:line IL_0040 mvid 999C
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in RunOrScheduleAction.il:line IL_003B mvid 999C
     at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in RunContinuations.il:line IL_0065 mvid 999C or RunContinuations.il:line IL_0090 mvid 999C
     at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute) in FinishSlow.il:line IL_0003 mvid 999C
     at System.Threading.Tasks.Task.TrySetException(Object exceptionObject) in TrySetException.il:line IL_0022 mvid 999C
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField) in SetException.il:line IL_0025 mvid 999C
     at JetBrains.ReSharper.UnitTestFramework.Execution.TestRunner.TestRunnerAgentManager.TestRunnerExecutionAgent.RunTests(CancellationToken cancelCt, CancellationToken abortCt) in RunTests.il:line IL_00AE mvid 4F79
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s) in ExecutionContextCallback.il:line IL_0000 mvid 999C
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in RunInternal.il:line IL_0040 mvid 999C
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in MoveNext.il:line IL_0000 mvid 999C or MoveNext.il:line IL_0040 mvid 999C
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in MoveNext.il:line IL_0000 mvid 999C or MoveNext.il:line IL_0040 mvid 999C
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in RunOrScheduleAction.il:line IL_003B mvid 999C
     at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in RunContinuations.il:line IL_0065 mvid 999C or RunContinuations.il:line IL_0090 mvid 999C
     at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute) in FinishSlow.il:line IL_0003 mvid 999C
     at System.Threading.Tasks.Task.TrySetException(Object exceptionObject) in TrySetException.il:line IL_0022 mvid 999C
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField) in SetException.il:line IL_0025 mvid 999C
     at JetBrains.ReSharper.UnitTestFramework.Common.Extensions.TaskExtensions.CancelIf(Task task, CancellationToken ct, TaskCreationOptions options) in CancelIf.il:line IL_0126 mvid 4F79
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s) in ExecutionContextCallback.il:line IL_0000 mvid 999C
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in RunInternal.il:line IL_0040 mvid 999C
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in MoveNext.il:line IL_0000 mvid 999C or MoveNext.il:line IL_0040 mvid 999C
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in MoveNext.il:line IL_0000 mvid 999C or MoveNext.il:line IL_0040 mvid 999C
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in RunOrScheduleAction.il:line IL_003B mvid 999C
     at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in RunContinuations.il:line IL_0065 mvid 999C or RunContinuations.il:line IL_0090 mvid 999C
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in TrySetResult.il:line IL_004B mvid 999C
     at System.Threading.Tasks.Task.TwoTaskWhenAnyPromise`1.Invoke(Task completingTask) in Invoke.il:line IL_0088 mvid 999C
     at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in RunContinuations.il:line IL_0065 mvid 999C or RunContinuations.il:line IL_0090 mvid 999C
     at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute) in FinishSlow.il:line IL_0003 mvid 999C
     at System.Threading.Tasks.Task.TrySetException(Object exceptionObject) in TrySetException.il:line IL_0022 mvid 999C
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField) in SetException.il:line IL_0025 mvid 999C
     at JetBrains.ReSharper.UnitTestFramework.Common.Extensions.TaskExtensions.ThrowIf[TException](Task task, Task signallingTask, Func`1 exceptionFactory) in ThrowIf.il:line IL_00A9 mvid 4F79
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s) in ExecutionContextCallback.il:line IL_0000 mvid 999C
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in RunInternal.il:line IL_0040 mvid 999C
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in MoveNext.il:line IL_0000 mvid 999C or MoveNext.il:line IL_0040 mvid 999C
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in MoveNext.il:line IL_0000 mvid 999C or MoveNext.il:line IL_0040 mvid 999C
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in RunOrScheduleAction.il:line IL_003B mvid 999C
     at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in RunContinuations.il:line IL_0065 mvid 999C or RunContinuations.il:line IL_0090 mvid 999C
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in TrySetResult.il:line IL_004B mvid 999C
     at System.Threading.Tasks.Task.TwoTaskWhenAnyPromise`1.Invoke(Task completingTask) in Invoke.il:line IL_0088 mvid 999C
     at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in RunContinuations.il:line IL_0065 mvid 999C or RunContinuations.il:line IL_0090 mvid 999C
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in TrySetResult.il:line IL_004B mvid 999C
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result) in SetExistingTaskResult.il:line IL_001D mvid 999C
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result) in SetResult.il:line IL_0015 mvid 999C
     at JetBrains.Util.ProcessExtensions.WaitForExitAsync(IPreparedProcess process, CancellationToken token) in WaitForExitAsync.il:line IL_018C mvid 6A61
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s) in ExecutionContextCallback.il:line IL_0000 mvid 999C
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in RunInternal.il:line IL_0040 mvid 999C
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in MoveNext.il:line IL_0000 mvid 999C or MoveNext.il:line IL_0040 mvid 999C
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in MoveNext.il:line IL_0000 mvid 999C or MoveNext.il:line IL_0040 mvid 999C
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in RunOrScheduleAction.il:line IL_003B mvid 999C
     at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in RunContinuations.il:line IL_0065 mvid 999C or RunContinuations.il:line IL_0090 mvid 999C
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in TrySetResult.il:line IL_004B mvid 999C
     at System.Threading.Tasks.TaskCompletionSource`1.TrySetResult(TResult result) in TrySetResult.il:line IL_0000 mvid 999C
     at JetBrains.Util.ProcessExtensions.<>c__DisplayClass3_0.<WaitForExitAsync>b__0(IPreparedProcess _, Int32 code) in ProcessExtensions.il:line IL_0000 mvid 6A61
     at JetBrains.Util.Processes.PreparedProcessWithCachedOutput.InnerOnExited(IPreparedProcess process, Int32 exitCode) in InnerOnExited.il:line IL_0067 mvid 6A61
     at JetBrains.ReSharper.UnitTestFramework.Common.Processes.PreparedProcess.OnExit(Object sender, EventArgs eventArgs) in OnExit.il:line IL_00A7 mvid 4F79
     at System.Diagnostics.Process.RaiseOnExited() in RaiseOnExited.il:line IL_0023 mvid 5BE9
     at System.Diagnostics.Process.CompletionCallback(Object waitHandleContext, Boolean wasSignaled) in CompletionCallback.il:line IL_001D mvid 5BE9
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in RunInternal.il:line IL_0040 mvid 999C
     at System.Threading.PortableThreadPool.CompleteWait(RegisteredWaitHandle handle, Boolean timedOut) in CompleteWait.il:line IL_0017 mvid 999C
     at System.Threading.ThreadPoolWorkQueue.Dispatch() in Dispatch.il:line IL_0150 mvid 999C
     at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in WorkerThreadStart.il:line IL_00A0 mvid 999C
     at System.Threading.Thread.StartCallback() in StartCallback.il:line IL_000E mvid 999C
”
```

**Comment by IlyaBausovAkvelon** [comment]
Hi @Moshex,
Thank you for reporting this. Let me take a look.

**Comment by IlyaBausovAkvelon** [comment]
Hi @Moshex,
We've fixed that in Xamarin.UITest 4.4.2. Could you please try it out?

**Comment by IlyaBausovAkvelon** [comment]
Closing this issue due to inactivity.

**Comment by Moshex** [comment]
This issue is fixed thank you!

**Comment by IlyaBausovAkvelon** [comment]
@Moshex,
Thanks for your feedback!
