### ISSUE TITLE
Xamarin.UITest error running Calabash query with Property("content-desc").Contains("...")

### ISSUE THREAD

**Issue by KthProg** [microsoft/appcenter#826]
**What App Center service does this affect?**
Xamarin.UITest

**Describe the bug**
Running this query causes an exception:
`Marked("IdHere").Descendant().Class("ListView").Descendant().Property("content-desc").Contains("PartialContentDescHere")`

**To Reproduce**
Run the above query on a component marked with an automation id, with a list view as a descendant. Within this list view, have components with automation ids that all contain some common text. Query the content-desc by that text (contains) on an Android device.

**Expected behavior**
The elements are found (as the query is correct).

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Smartphone (please complete the following information):**
 - Device: LG Stylo 3+
 - OS: Android
 - Version 7

**Additional context**
Stack trace:
```05-08-2019 16:43:28.410 -04:00 - 79286 - HTTP POST { Url: { AbsolutePath: "/map", AbsoluteUri: "http://127.0.0.1:63023/map", LocalPath: "/map", Authority: "127.0.0.1:63023", HostNameType: IPv4, IsDefaultPort: False, IsFile: False, IsLoopback: True, PathAndQuery: "/map", Segments: [ "/", "map" ], IsUnc: False, Host: "127.0.0.1", Port: 63023, Query: "", Fragment: "", Scheme: "http", OriginalString: "http://127.0.0.1:63023/map", DnsSafeHost: "127.0.0.1", IdnHost: "127.0.0.1", IsAbsoluteUri: True, UserEscaped: False, UserInfo: "" } }
05-08-2019 16:43:45.049 -04:00 - 95925 - Error while performing Query(Marked("DevicesDock").Descendant().Class("ListView").Descendant().Property("content-desc").Contains("Cell"))
Exception: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The server returned an invalid or unrecognized response
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at Xamarin.UITest.Shared.Http.HttpClient.SendData(String endpoint, String method, HttpContent content, ExceptionPolicy exceptionPolicy, Nullable`1 timeOut)
   at Xamarin.UITest.Shared.Http.HttpClient.Post(String endpoint, String arguments, ExceptionPolicy exceptionPolicy, Nullable`1 timeOut)
   at Xamarin.UITest.Android.AndroidGestures.Query[T](ITokenContainer query, Object[] args, String methodName)
   at Xamarin.UITest.Android.AndroidGestures.Query(AppQuery query)
   at Xamarin.UITest.Android.AndroidApp.<>c__DisplayClass12_0.<Query>b__0()
   at Xamarin.UITest.Utils.ErrorReporting.With[T](Func`1 func, Object[] args, String memberName)
05-08-2019 16:43:45.060 -04:00 - 95935 - HTTP POST { Url: { AbsolutePath: "/map", AbsoluteUri: "http://127.0.0.1:63023/map", LocalPath: "/map", Authority: "127.0.0.1:63023", HostNameType: IPv4, IsDefaultPort: False, IsFile: False, IsLoopback: True, PathAndQuery: "/map", Segments: [ "/", "map" ], IsUnc: False, Host: "127.0.0.1", Port: 63023, Query: "", Fragment: "", Scheme: "http", OriginalString: "http://127.0.0.1:63023/map", DnsSafeHost: "127.0.0.1", IdnHost: "127.0.0.1", IsAbsoluteUri: True, UserEscaped: False, UserInfo: "" } }
05-08-2019 16:43:45.109 -04:00 - 95984 - Error while performing Query(Marked("DevicesDock").Descendant().Class("ListView").Descendant().Property("content-desc").Contains("Cell"))
Exception: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The connection with the server was terminated abnormally
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at Xamarin.UITest.Shared.Http.HttpClient.SendData(String endpoint, String method, HttpContent content, ExceptionPolicy exceptionPolicy, Nullable`1 timeOut)
   at Xamarin.UITest.Shared.Http.HttpClient.Post(String endpoint, String arguments, ExceptionPolicy exceptionPolicy, Nullable`1 timeOut)
   at Xamarin.UITest.Android.AndroidGestures.Query[T](ITokenContainer query, Object[] args, String methodName)
   at Xamarin.UITest.Android.AndroidGestures.Query(AppQuery query)
   at Xamarin.UITest.Android.AndroidApp.<>c__DisplayClass12_0.<Query>b__0()
   at Xamarin.UITest.Utils.ErrorReporting.With[T](Func`1 func, Object[] args, String memberName)
05-08-2019 16:43:45.121 -04:00 - 95996 - Error while performing ScrollUpTo([unknown], null, Auto, 0.67, 500, True, null)
Exception: System.Exception: Error while performing Query(Marked("DevicesDock").Descendant().Class("ListView").Descendant().Property("content-desc").Contains("Cell")) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The server returned an invalid or unrecognized response
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at Xamarin.UITest.Shared.Http.HttpClient.SendData(String endpoint, String method, HttpContent content, ExceptionPolicy exceptionPolicy, Nullable`1 timeOut)
   at Xamarin.UITest.Shared.Http.HttpClient.Post(String endpoint, String arguments, ExceptionPolicy exceptionPolicy, Nullable`1 timeOut)
   at Xamarin.UITest.Android.AndroidGestures.Query[T](ITokenContainer query, Object[] args, String methodName)
   at Xamarin.UITest.Android.AndroidGestures.Query(AppQuery query)
   at Xamarin.UITest.Android.AndroidApp.<>c__DisplayClass12_0.<Query>b__0()
   at Xamarin.UITest.Utils.ErrorReporting.With[T](Func`1 func, Object[] args, String memberName)
   --- End of inner exception stack trace ---
   at Xamarin.UITest.Utils.ErrorReporting.With[T](Func`1 func, Object[] args, String memberName)
   at Xamarin.UITest.Android.AndroidApp.Query(Func`2 query)
   at OCUnitTests.Common.Element.ComponentDescendantsByPartialId[TComponent](String partialAutomationId)
   at OCUnitTests.POM.Components.ListViewComponent`1.get_Cells()
   at OCUnitTests.POM.Components.ListViewComponent`1.<ScrollUp>b__7_0(AppQuery q)
   at Xamarin.UITest.SharedApp.LogWithToQueryWithinQuery(String message, Func`2 toQuery, Func`2 withinQuery)
   at Xamarin.UITest.SharedApp.ScrollUpTo(Func`2 toQuery, Double swipePercentage, Int32 swipeSpeed, Func`2 withinQuery, ScrollStrategy strategy, Boolean withInertia, Nullable`1 timeout)
   at Xamarin.UITest.Android.AndroidApp.<>c__DisplayClass55_0.<ScrollUpTo>b__0()
   at Xamarin.UITest.Utils.ErrorReporting.With(Action func, Object[] args, String memberName)
05-08-2019 16:44:42.995 -04:00 - 153870 - Finished with exit code 0 in 1399 ms.
```

**Comment by KthProg** [comment]
It seems like it must be generating an invalid Calabash query, but the logs don't expose the POST data so it's hard to say.

**Comment by KthProg** [comment]
Here's the text query:
`* marked:'[Id]' descendant * [ClassName] descendant * {content-desc CONTAINS '[PartialId]'}`

**Comment by KthProg** [comment]
I figured it out. In Calabash, the property is called "contentDescription". Is this information documented anywhere?
