### ISSUE TITLE
AppCenter.Start failed on WinForms with System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by StefanKoell** [microsoft/appcenter#845]
**What App Center service does this affect?**
Analytics on WinForms

**Describe the bug**
When an app is deployed to the user, AppCenter doesn't work because it tries to write temporary files to the install directory (usually C:\Program Files (x86)\some path

**To Reproduce**
Build a WinForms app which uses Analytics
Deploy it to the Program Files directory
Start the app as user (without elevated or admin rights)

**Expected behavior**
I expect that the Sdk uses a temp directory where the user has write access or even better, provide a way to configure the temp path.

**Desktop (please complete the following information):**
 - OS: Windows 10 - 1903

**Additional context**
Feature tracking: AppCenter.Start failed.

System.TypeInitializationException: The type initializer for 'Microsoft.AppCenter.Utils.Constants' threw an exception. ---&gt; System.Configuration.ConfigurationErrorsException: An error occurred loading a configuration file: Access to the path 'C:\Program Files (x86)\[app name]\0sjgikzk.tmp' is denied. (C:\Program Files (x86)\[app name]\AppCenter.config) ---&gt; System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\[app name]\0sjgikzk.tmp' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.CodeDom.Compiler.TempFileCollection.EnsureTempNameCreated()
   at System.CodeDom.Compiler.TempFileCollection.AddExtension(String fileExtension, Boolean keepFile)
   at System.Configuration.Internal.WriteFileContext..ctor(String filename, String templateFilename)
   at System.Configuration.Internal.InternalConfigHost.StaticOpenStreamForWrite(String streamName, String templateStreamName, Object&amp; writeContext, Boolean assertPermissions)
   at System.Configuration.Internal.InternalConfigHost.System.Configuration.Internal.IInternalConfigHost.OpenStreamForWrite(String streamName, String templateStreamName, Object&amp; writeContext)
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   --- End of inner exception stack trace ---
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   at Microsoft.AppCenter.Utils.DefaultApplicationSettings.SaveValue(String key, String value)
   at Microsoft.AppCenter.Utils.DefaultApplicationSettings.SetValue(String key, Object value)
   at Microsoft.AppCenter.Utils.DefaultApplicationSettings.GetValue[T](String key, T defaultValue)
   at Microsoft.AppCenter.AppCenter.PlatformGetInstallIdAsync()
   at Microsoft.AppCenter.Utils.Constants.get_AppCenterFilesDirectoryPath()
   at Microsoft.AppCenter.Utils.Constants..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.AppCenter.Storage.Storage.DefaultAdapter()
   at Microsoft.AppCenter.AppCenter.InstanceConfigure(String appSecretOrSecrets)
   at Microsoft.AppCenter.AppCenter.PlatformStart(String appSecret, Type[] services)

**Comment by rjschnorenberg** [comment]
This can be worked around by implementing a custom IApplicationSettingsFactory.
```
AppCenter.SetApplicationSettingsFactory(new ApplicationSettingsFactory());
AppCenter.Start(APP_CENTER_ID, typeof(Microsoft.AppCenter.Analytics.Analytics), typeof(Microsoft.AppCenter.Crashes.Crashes));
```

```
public class ApplicationSettingsFactory : IApplicationSettingsFactory
{
	public IApplicationSettings CreateApplicationSettings()
	{
		return new ApplicationSettings();
	}
}

public class ApplicationSettings : IApplicationSettings
{
	// Implement interface here. I looked at the reflected source code of Microsoft.AppCenter.Utils.DefaultApplicationSettings for guidance (you can see the bug there in OpenConfiguration where it uses the executing assembly's location to put the AppCenter.config).
}
```

**Comment by AnastasiaKubova** [comment]
Hi there! This issue has been fixed.
I'm closing this issue but feel free to open a new issue on the [appcenter-sdk-dotnet](https://github.com/microsoft/appcenter-sdk-dotnet) repository if this issue still persists.
