### ISSUE TITLE
[AppCenter] java.net.SocketTimeoutException: SSL handshake timed out

### ISSUE THREAD

**Issue by spatialguy** [microsoft/appcenter#851]
I my xamarin.forms app (android), my crashes does not appear in appcenter web console. I just tested it by generating test crash.
I see a lot of errors in the log file:

```
[AppCenter] Try #1 failed and will be retried in 8899 ms
[AppCenter] java.net.SocketTimeoutException: SSL handshake timed out
[AppCenter] 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
[AppCenter] 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
[AppCenter] 	at com.android.okhttp.Connection.connectTls(Connection.java:235)
[AppCenter] 	at com.android.okhttp.Connection.connectSocket(Connection.java:199)
[AppCenter] 	at com.android.okhttp.Connection.connect(Connection.java:172)
[AppCenter] 	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
[AppCenter] 	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
[AppCenter] 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
[AppCenter] 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
[AppCenter] 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
[AppCenter] 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
[AppCenter] 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:257)
[AppCenter] 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
[AppCenter] 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
[AppCenter] 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doHttpCall(DefaultHttpClientCallTask.java:277)
[AppCenter] 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:328)
[AppCenter] 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:47)
[AppCenter] 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
[AppCenter] 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
[AppCenter] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
[AppCenter] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
[AppCenter] 	at java.lang.Thread.run(Thread.java:761)
```

Appcenter sttus page says "All Systems Operational"
https://kkc10kz2t8yc.statuspage.io/

**Comment by wedmak** [comment]
I have the same problem on xamarin forms (android). 
08-09 15:07:44.488 W/AppCenter(28658): Try #1 failed and will be retried in 8583 ms
08-09 15:07:44.488 W/AppCenter(28658): java.net.SocketTimeoutException: SSL handshake timed out
08-09 15:08:53.246 W/AppCenter(28658): Try #2 failed and will be retried in 190071 ms
08-09 15:08:53.246 W/AppCenter(28658): java.net.SocketTimeoutException: failed to connect to in.appcenter.ms/104.208.240.18 (port 443) from /192.168.43.245 (port 43578) after 60000ms

**Comment by yoannchaudet** [comment]
Hello,

Can you reproduce the issue? This looks related to [this past incident](https://status.appcenter.ms/incidents/7vcg4k0fb1c2) that made our ingestion endpoint unavailable for a short moment.

SDK are expected to keep logs on local storage and send them at a later time.

**Comment by DaveBrickley** [comment]
I am getting this issue 100% on startup of a Xamarin Android project consuming the App Center module

**Comment by MatkovIvan** [comment]
@DaveBrickley please check the date and time on the device (it's required for https connection). If it's still the problem, please open support ticket on the portal. Thanks

**Comment by DaveBrickley** [comment]
@MatkovIvan Date and time on the physical device appear to be correc

**Comment by CatsNipYummy** [comment]
Is this issue still present? I get the same error:

`
W/AppCenter: Try #1 failed and will be retried in 5767 ms
    java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:215)
        at java.net.SocketInputStream.read(SocketInputStream.java:144)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:722)
        at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
        at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
        at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:1450)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:1399)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:1343)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:221)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:144)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:106)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:400)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:333)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
        at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doHttpCall(DefaultHttpClientCallTask.java:226)
        at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:279)
        at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:48)
`
