### ISSUE TITLE
.NET 6

### ISSUE THREAD

**Issue by VladislavAntonyuk** [microsoft/appcenter#86]
We have updated our project to .net 5 preview. But CI doesn't support it (.net core 3 is the latest). Please add support for .net 5

**Comment by VladislavAntonyuk** [comment]
Any updates?

**Comment by wham** [comment]
We are working on .NET 5.0 support. Should be available by the end of the year.

**Comment by wham** [comment]
We added .NET 5.0 this week. Please let us know if you notice any issues.

**Comment by dersia** [comment]
I just tried to run my pipeline again I am still getting an error `CSC : error CS1617: Invalid option '9' for /langversion.`
I updated the Xamarin.iOS version to 14.6

**Comment by wham** [comment]
Thanks for reporting. We'll take another look.

**Comment by dersia** [comment]
This might help https://stackoverflow.com/questions/65309660/csc-on-macos-does-not-list-c-sharp-9

**Comment by MasterEmit** [comment]
I know this appcenter related and not azure devops, but I have the exact same problem with azure devops pipeline. Any idea how to solve that? Workaround? 

Thanks and Greetz

**Comment by AlenaSviridenko** [comment]
Hi @MasterEmit, @dersia,
could you please provide minimal steps to reproduce, so we can make sure the issue is related to the image and not to the project configuration? Also, it will help us to investigate the issue deeper.
All our internal tests passed successfully for a variety of different projects.

Thank you.

**Comment by DenLavrov** [comment]
Same issue here. Any updates?

**Comment by chrisstaley** [comment]
I'm trying to compile a Xamarin Android app that references a .NET Standard library whose LangVersion is set to 9, and I'm getting the same error.

```XML
<PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <DebugType>portable</DebugType>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <Configurations>Debug;Test</Configurations>
    <LangVersion>9</LangVersion>
  </PropertyGroup>
```

**Comment by AdamDiament** [comment]
I have the same issue. My C Sharp 9 code has stopped compiling on app center android.

**Comment by AlenaSviridenko** [comment]
Hi folks,
Could you please share some repro steps? It would really help us investigate this issue deeper, because all our internal tests are passed, and we are not getting a lot of feedbacks about broken .NET 5 (which can be expected if there were some obvious and easily reproducible issue)

Thanks!

**Comment by chrisstaley** [comment]
@AlenaSviridenko I included the elements in the csproj file that will cause the failure. So repro steps would be:
1. Create .NET Standard assembly project with those elements.
2. Create Android app.
3. Make #2 reference #1.
4. Build in AppCenter.

**Comment by AdamDiament** [comment]
Repro: 
1. Create a .net standard 2.0 assembly project, set <LangVersion>Latest</LangVersion> in the cS proj
2. Create xamarin android project, referencing the project in step 1.
3. In step 1, add a file containing any C#9 syntax, for instance advanced pattern matching or the new switch statements with operators in it
4. Build locally - it will build
5. Push to app center, it will fail

**Comment by dersia** [comment]
Sorry it took me some time to come back to you.

Basically you just need a csproj file that has the following flag
```xml
<LangVersion>9</LangVersion>
```

I found a workaround for those who are still looking, but it only works with a custom build script (github action, azure pipelines)

# Workaround
## iOS
```sh
mono '/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/msbuild.dll' /p:Configuration=Release /p:Platform=iPhone <path/to/solutionfile.sln>
```

## Android
run for android
```sh
mono '/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/msbuild.dll' /p:Configuration=Release /p:Platform=PackageForAndroid <path/to/android/project.csproj>
```

# Why it works
using the MSBuild from the Path `/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/` uses the MSBuild thats part of Visual Studio for Mac. VS4Mac has already c# 9 support, although mono does not. So this way you can compile C# 9 and .net5 code

Hope this helps

**Comment by ahmedalejo** [comment]
> Hi folks,
> Could you please share some repro steps? It would really help us investigate this issue deeper, because all our internal tests are passed, and we are not getting a lot of feedbacks about broken .NET 5 (which can be expected if there were some obvious and easily reproducible issue)
> 
> Thanks!

I´m not sure where your metrics are coming from but you should have noticed that there is a spike in build failures due to C# 9.0 syntax issues.

`##[error]Error: The process '/Library/Frameworks/Mono.framework/Versions/6_12_3/bin/msbuild' failed with exit code 1`

I had the following in my Xamarin.Forms app

```csharp
if (e.Source is ShellNavigationSource.Pop or ShellNavigationSource.PopToRoot  or ShellNavigationSource.Remove)
{...}
```
Visual Studio Mac which is installed on Mac Build Agents could/should be used for building the dlls.
Or simply allowed as an alternative to using Mono directly.

**Comment by AdamDiament** [comment]
@dersia thanks for the workaround. What exactly do I do with your 

mono '/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/msbuild.dll' /p:Configuration=Release /p:Platform=iPhone <path/to/solutionfile.sln>


Is this a build script I need to add in app center, or something in VS, or something else entirely?

**Comment by dersia** [comment]
@AdamDiament 
This is basically the Build-Step within your Build-Script. Unfortunately you can't run your own Build-Scripts directly in AppCenter at least as far as I know, so you will need another build-pipeline, that builds your app and then in another step pushes it to AppCenter. You can use either Github-Actions or Azure (DevOps) Pipelines.

If you need further help, please let me know.

**Comment by varyamereon** [comment]
> @AdamDiament
> This is basically the Build-Step within your Build-Script. Unfortunately you can't run your own Build-Scripts directly in AppCenter at least as far as I know, so you will need another build-pipeline, that builds your app and then in another step pushes it to AppCenter. You can use either Github-Actions or Azure (DevOps) Pipelines.
> 
> If you need further help, please let me know.

@dersia If I am right then AppCenter [does support build scripts](https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/). I have never used build scripts before, is it just a case of copying the line of code into an appcenter-pre-build.sh file? What would the path to solution file be then?

Thanks!

**Comment by jvillaro** [comment]
Hi guys, any updates?

**Comment by Clement-Vivier** [comment]
> Sorry it took me some time to come back to you.
> 
> Basically you just need a csproj file that has the following flag
> 
> ```
> <LangVersion>9</LangVersion>
> ```
> 
> I found a workaround for those who are still looking, but it only works with a custom build script (github action, azure pipelines)
> 
> # Workaround
> ## iOS
> ```shell
> mono '/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/msbuild.dll' /p:Configuration=Release /p:Platform=iPhone <path/to/solutionfile.sln>
> ```
> 
> ## Android
> ```shell
> mono '/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/msbuild.dll' /p:Configuration=Release /p:Platform=PackageForAndroid <path/to/android/project.csproj>
> ```
> 
> # Why it works
> using the MSBuild from the Path `/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/` uses the MSBuild thats part of Visual Studio for Mac. VS4Mac has already c# 9 support, although mono does not. So this way you can compile C# 9 and .net5 code
> 
> Hope this helps

Hello ! I struggle with your workaround, I'm basically trying to do the same, an azure pipeline who take a Xamarin forms 5.0 project in C#9 and every time I try to do the mono script that you give for android, I got an error, with 

` /Users/runner/.nuget/packages/xamarin.forms/5.0.0.2012/buildTransitive/Xamarin.Forms.targets(125,4): error MSB4064: The "ValidateOnly" parameter is not supported by the "XamlCTask" task. Verify the parameter exists on the task, and it is a settable public instance property.`
With a csproj given after that, i check in this csproj file, and I never use stuff like "ValidateOnly" after many times on Google someone has the same error within visual studio, but I find no one with this error on an azure pipeline. 
If you have any cloud, of what could be at the origin of this error. That will be a life safer to me. 

Clément.

**Comment by beeradmoore** [comment]
@wham @nilofer  6 months since it was understood that this was going to be looked into. Is there any update on it?

@derana  I appreciate the workaround. However, setting up a new CI/CD pipeline on an alternative service isn't a workaround as much as it is jumping ship.

**Comment by jvillaro** [comment]
Recently in one of the updates I saw that there was a way to eliminate the bar. Someone removed the default "Sign In" message and showed how to remove the bar via android manifest.
It's not the ideal way but it worked.
I need to try still on iOS

**Comment by ederbond** [comment]
@wham @davidortinau  @maddyleger1 @hartez @StephaneDelcroix @jsuarezruiz  do you have any news about when will be possible to build Xamarin Forms projects on AppCenter using the new C# 9 syntax on our code? 
currently delcaring field on any of my own call like below fails to build on AppCenter

`MyClass _obj = new();`

**Comment by GLBekker** [comment]
Good afternoon is anyone looking into this ? We are still having trouble building Lang 9 via App Center.

**Comment by martin-slater** [comment]
+1 for some movement on this. Has been nearly 2.5 years

**Comment by AdamDiament** [comment]
Still an issue for me. Bump. I'd like to be able to use C#10 soon too!

**Comment by Safeer-Ahmad** [comment]
Over 2 years and still no update on this. Any workaround??

**Comment by DeltaJulio** [comment]
See #2120 for workarounds to use C# 9 in AppCenter.

**Comment by martin-slater** [comment]
Bouncing this to keep it open. Come on, I pay for it,  you update it!

**Comment by AdamDiament** [comment]
Bump!

**Comment by marekdovjak** [comment]
+1

**Comment by santihcc** [comment]
+1

**Comment by santihcc** [comment]
+1

**Comment by KerosenoDev** [comment]
+1

**Comment by AnastasiaKubova** [comment]
Hi there! Thanks for your interest in the feature! Please use reactions instead of `+1`.

**Comment by nabeelio** [comment]
Any updates on this?

Using:
```xml
<TargetFrameworks>net5.0-windows10.0.18362.0</TargetFrameworks>
```

For WinRT support with ModernWPF. Getting this:

```Acars.App.HandleExceptionCatch:294 UncaughtException:: (unwind) System.InvalidOperationException
Acars.App.HandleExceptionCatch:298 UnhandledException StackTrace :    at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageStaticsMethods.get_Current(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_Current()
   at Microsoft.AppCenter.Utils.DeviceInformationHelper.GetAppVersion()
   at Microsoft.AppCenter.Utils.AbstractDeviceInformationHelper.GetDeviceInformation()
   at Microsoft.AppCenter.Utils.AbstractDeviceInformationHelper.<GetDeviceInformationAsync>b__9_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)```

**Comment by RemcoDEV** [comment]
When is App Center going to install .NET 6 SDKs to their build servers? Currently we can only choose between:
3.1.101
3.1.201
3.1.302
3.1.416
5.0.102
5.0.202
5.0.302
5.0.405

**Comment by ericbrunner** [comment]
still not on .NET 6

**Comment by mphill** [comment]
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

.NET 5 support ends May 8, 2022, and .NET 6 isn't supported yet...............

One of the issues is AppCenter processes the entire solution, so if you have an API in your project that targets .NET 6 your mobile apps will not build.

This is very problematic.

**Comment by Mephisztoe** [comment]
When trying to run a .NET 6 iOS app with AppCenter installed, I receive the following error message:

![Exception_ios](https://user-images.githubusercontent.com/5309613/168426021-c6702618-2a61-4599-accd-fd471130f19d.png)

**Comment by Brosten** [comment]
As for the workaround, after vs2022 was installed on MacOS images, msbuild can now be found here:
/Applications/Visual\ Studio.app/Contents/MonoBundle/MSBuild/Current/bin/MSBuild.dll

**Comment by softlion** [comment]
The current nugets don't work with net6-ios / net6-android

Any clue ?

https://github.com/dotnet/maui/discussions/9027

**Comment by themronion** [comment]
> As for the workaround, after vs2022 was installed on MacOS images, msbuild can now be found here: /Applications/Visual\ Studio.app/Contents/MonoBundle/MSBuild/Current/bin/MSBuild.dll

So, we need to switch the default msbuild path to this one? Can u share how you can do it in an script for App Center?

**Comment by ECDev01** [comment]
> > As for the workaround, after vs2022 was installed on MacOS images, msbuild can now be found here: /Applications/Visual\ Studio.app/Contents/MonoBundle/MSBuild/Current/bin/MSBuild.dll
> 
> So, we need to switch the default msbuild path to this one? Can u share how you can do it in a script for App Center?

Still no luck? any solution?

**Comment by ECDev01** [comment]
> As for the workaround, after vs2022 was installed on MacOS images, msbuild can now be found here: /Applications/Visual\ Studio.app/Contents/MonoBundle/MSBuild/Current/bin/MSBuild.dll

I have been talking to appcenter support team but not luck, their workaround keeps failing, I am not sure if they are really trying to help me or they are just wasting my time.

To change MSBuild path, Is it possible in AppCenter? If so, can you please show how? Thanks.

**Comment by ericbrunner** [comment]
@ECDev01 As you, I had no luck on that issue with appcenter support. I ended up with building the app in Azure DevOps (CI) and uploaded the app with the appcenter deployment task (CD): https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/app-center-distribute

They can provide you a Pre-Build script to install .NET SDK of your choice. I tried such one with .NET 6.0 but without success and because of lack of time, I took the other approach with deployment task.

Hope that helps :-)

**Comment by themronion** [comment]
For anyone still seeking how to support c#10 in App Center - u need to find an msbuild file in your system, copy it and change the second path there to the location of MSBuild.dll that is bundled with VS 2022. Then, in a post-clone script copy this file from your project's directory to the directory where you've found it on your system. Voila, there u have it. Welcome and enjoy

**Comment by ECDev01** [comment]
> @ECDev01 As you, I had no luck on that issue with appcenter support. Here are workarounds:
> 
> I ended up with building the app in Azure DevOps (CI) and uploaded the app with the appcenter deployment task (CD): https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/app-center-distribute
> 
> They can provide you a Pre-Build script to install .NET SDK of your choice:
> 
> https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/#pre-build
> 
> I tried such one with .NET 6.0 but without success and because of lack of time, I took the other approach with deployment task.
> 
> Hope that helps :-)

Thanks mate, I am so close to do this but first I will try @themronion otherwise good bye AppCenter!

**Comment by ECDev01** [comment]
> For anyone still seeking how to support c#10 in App Center - u need to find an msbuild file in your system, copy it and change the second path there to the location of MSBuild.dll that is bundled with VS 2022. Then, in a post-clone script copy this file from your project's directory to the directory where you've found it on your system. Voila, there u have it. Welcome and enjoy

Hi @themronion, 

When you say "...find a msbuild file in your system...", are you talking about MSBuild.exe or MSBuild.dll or any of them? Btw, I can find both of them. 
MSBuild.exe (D:\Program Files\Microsoft Visual Studio\2022\Professional\Msbuild\Current\Bin)
MSBuild.dll (D:\Program Files\dotnet\sdk\6.0.202)
What do you mean with "...change the second path there to the location of MSBuild.dll that is bundled with VS 2022..."?

Thanks for your help!

**Comment by themronion** [comment]
@ECDev01 my instructions are for a mac build agent and a macos system respectively

**Comment by CharlyZest** [comment]
So there will be no support for .NET MAUI?

**Comment by CharlyZest** [comment]
So there will be no official support for .NET MAUI?

**Comment by CharlyZest** [comment]
So there will be no official support for .NET MAUI?

**Comment by softlion** [comment]
> So there will be no official support for NET MAUI with NET 6?

You can do the same with github actions, at x10 the price of appcenter (mac vm on github actions consumes x10 credits), and with a non intuitive and complicated UI and scripts (appcenter is simple to use, github actions are horrible).

**Comment by ECDev01** [comment]
I asked for help to appcenter support and they recommend Azure Pipelines, basically @ericbrunner suggestion, by the way, trying to install .NET 6 didn't work at all. Anyway, creating the pipeline for the building process is enough, so now I am building my app using Azure Pipelines (yaml) and the distribution is handled by appcenter.

**Comment by EdwardMcFlurry** [comment]
Any idea why iOS crashes when Android works well with AppCenter on .Net 6???

**Comment by EmilAlipiev** [comment]
> Any idea why iOS crashes when Android works well with AppCenter on .Net 6???

This is good question and bugs me. I have a unit test project on .net 6 in xamarin.forms project. Basically looks like this
- XF shared (.net standard 2.0)
- Xamarin IOS
- Xamarin Android
- Unit test (.net 6)

On my build configuration, i have excluded  Unit test project and I have choosen Project to be build as "IOS" project but Appcenter build is failing as ".net 6" not supported. Obviously there is a bug for IOS builds  whatever you choose, it build all projects in the Project solution. 
 it all works fine on Android build.

**Comment by omatrot** [comment]
> For anyone still seeking how to support c#10 in App Center - u need to find an msbuild file in your system, copy it and change the second path there to the location of MSBuild.dll that is bundled with VS 2022. Then, in a post-clone script copy this file from your project's directory to the directory where you've found it on your system. Voila, there u have it. Welcome and enjoy

Hi,
Could you please be a little more specific about this workaround, giving us sample paths and instructions that worked for you, as I hope it would help me solve .NET 6 iOS support on AppCenter.

Thanks in advance.

**Comment by mphill** [comment]
We tried to do this (https://codetraveler.io/2019/08/23/using-preview-versions-of-net-core-with-app-center-build/
) to get .net 6 working on app center, but it still fails.  The post-clone seemed promising but it doesn't work. I think app center has .net 5 hard coded in for the build step.

I don't even need .net 6 for our Xamarin app, but we have our API project in the same solution file - and app center tries to restore it.    This has forced us to stick with .net 5 for our API. 

Does any know how to work around this? I'd like to upgrade our APIs to .net 6 but app center builds then fail.

**Comment by omatrot** [comment]
I've tried to import the build definition into Azure DevOps after it has been exported from AppCenter.
But the problem remains, at the restore nuget task:

```
Starting: Restore Nuget
==============================================================================
Task         : Command Line
Description  : Run a command line with arguments
Version      : 1.1.3
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
==============================================================================
/bin/bash -c nuget restore 'TestApplication.sln' -DisableParallelProcessing
(node:1773) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1773) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1773) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1773) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1773) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1773) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1773) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1773) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1773) Warning: Use Cipheriv for counter mode of aes-256-ctr
MSBuild auto-detection: using msbuild version '15.0' from '/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/15.0/bin'.
/Users/runner/hostedtoolcache/dotnet/sdk/5.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(141,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 6.0.  Either target .NET Core 5.0 or lower, or use a version of the .NET SDK that supports .NET Core 6.0. [/Users/runner/work/1/s/TestApplication/TestApplication.csproj]

##[error]/bin/bash failed with return code: 1
##[error]/bin/bash failed with error: /bin/bash failed with return code: 1
Finishing: Restore Nuget

```

So this is not related to AppCenter only, because of course, it is backed up by the Azure Devops infrastructure.
No surprise here, but a solution should be provided.

**Comment by jl-mobitech** [comment]
Still no updates? You guys promoting app center and maui and c# 10 and here we are in this issue :) Looks like MS does not care to the consumers :) y'all just promoting bunch of stuff that will be broke some time soon

**Comment by Umer-Mahmood-889** [comment]
Any updates on this?

**Comment by spatialdude** [comment]
See also #2500 which may be related to this issue, although I find Android, Windows and iOS targets are working with .NET MAUI + .NET 7, the problem is only with MacCatalyst.

**Comment by wisdeom** [comment]
Hi all! We support .NET 6 and MAUI in our latest SDK 5.0.1. Check out this release and let us know if you have any feedback. We'd love to hear from you. https://github.com/Microsoft/AppCenter-SDK-DotNet/releases

**Comment by mphill** [comment]
@omatrot Since it appears that App Center is now abandonware try to add this to your pipeline:

```yaml
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
```

**Comment by EmilAlipiev** [comment]
> UI in our latest SDK 5.0.1. Check out this release and let us know if you have any feedback. We'd love to hear from you. https://github.com/Microsoft/AppCenter-SDK-DotNet/releases

that may solve the problem with Maui but how does this resolve issue with the Unit-tests targeting .net 6? Please see my other comment below.

> > Any idea why iOS crashes when Android works well with AppCenter on .Net 6???
> 
> This is good question and bugs me. I have a unit test project on .net 6 in xamarin.forms project. Basically looks like this
> 
> * XF shared (.net standard 2.0)
> * Xamarin IOS
> * Xamarin Android
> * Unit test (.net 6)
> 
> On my build configuration, i have excluded Unit test project and I have choosen Project to be build as "IOS" project but Appcenter build is failing as ".net 6" not supported. Obviously there is a bug for IOS builds whatever you choose, it build all projects in the Project solution. it all works fine on Android build.

**Comment by dedtechsolutions** [comment]
Eu tenho o aplicativo ASP.NETCore net6 e no Windows AppCenter falha ao iniciar ...

**Comment by isax5** [comment]
I can't compile with C# 10 and 11 yet, is everything too updated for AppCenter or what??

**Comment by beeradmoore** [comment]
Bump

**Comment by EmilAlipiev** [comment]
> > Any idea why iOS crashes when Android works well with AppCenter on .Net 6???
> 
> This is good question and bugs me. I have a unit test project on .net 6 in xamarin.forms project. Basically looks like this
> 
> * XF shared (.net standard 2.0)
> * Xamarin IOS
> * Xamarin Android
> * Unit test (.net 6)
> 
> On my build configuration, i have excluded Unit test project and I have choosen Project to be build as "IOS" project but Appcenter build is failing as ".net 6" not supported. Obviously there is a bug for IOS builds whatever you choose, it build all projects in the Project solution. it all works fine on Android build.

This is really getting worse and worse. Now Appcenter team changed something and i am getting error even for Android. Although my Build Configuration is targeting .Android.csproj not the solution file, Appcenter is building entire solution by ignoring the configuration file. 

I can see that Appcenter uses a bash script that restores nuget and builds entire solution, not the specified Project in the configuration.
So if you are building Android, you can see in the logs that Nuget Restore and build is running also for IOS.

**Comment by beeradmoore** [comment]
AFAIK the downloading of all nugets isn't new.

We have post clone scripts that will delete other csproj files that we don't need restored. I'll try dig them up later when I am at my PC.

**Comment by beeradmoore** [comment]
This is our `appcenter-post-clone.sh` for our Android app. iOS app is similar but in reverse. Just update the `.csproj` and `.sln` and put it next to your `MYAPP.Droid.csproj`

```shell
#!/usr/bin/env bash
# App Center custom build scripts: https://aka.ms/docs/build/custom/scripts

echo "Disabling MYAPP.iOS.csproj to avoid updating nugets."

# Delete MYAPP.iOS from MYAPP.Forms.sln 
SLN_PATH=$BUILD_REPOSITORY_LOCALPATH/Software/MYAPP.Forms.sln
sed -i.bak '/MYAPP.iOS/{N;d;}' $SLN_PATH
rm -f ${SLN_PATH}.bak

# Delete MYAPP.iOS.csproj from the disk.
rm -f $BUILD_REPOSITORY_LOCALPATH/Software/MYAPP.Forms/MYAPP.iOS/MYAPP.iOS.csproj
```

**Comment by faze79** [comment]
> I have ASP.NETCore net6 application and in windows AppCenter fail to start...

We have net 8 but this library still not support net 6 this is really frustrating...
