### ISSUE TITLE
Microsoft.AppCenter WPF 2.2.1-preview Crash on start after installed

### ISSUE THREAD

**Issue by PieEatingNinjas** [microsoft/appcenter#865]
**What App Center service does this affect?**
2.2.1-preview WPF

**Describe the bug**
Application crashes when calling AppCenter.Start, after the application is installed via msix (self signed). No problem whatsoever when running from Visual Studio (2019), both in debug and release. Also no problem when running the exe directly. 

**To Reproduce**
1. Create new WPF project
2. Add Microsoft.AppCenter.Crashes nuget
3. Add AppCenter.Start("[a valid appcenter key]", typeof(Crashes)); to the App OnStartup method 
4. Add Windows Application Packaging Project (Target 1903, Min 1809)
5. Add reference to WPF project
6. Update Publisher in Package.appxmanifest to match your signing certificate
7. Right-click Packaging project -> Store -> Create App Package... 
8. Choose Sideloading, select certificate (sefl-signed), Create
9. Double-click the resulting msixbundle file -> Install
10. **Application doesn't start**

**EventLog**
```
Application: AppCenterWPF.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UnauthorizedAccessException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess)
   at System.CodeDom.Compiler.TempFileCollection.EnsureTempNameCreated()
   at System.CodeDom.Compiler.TempFileCollection.AddExtension(System.String, Boolean)
   at System.Configuration.Internal.WriteFileContext..ctor(System.String, System.String)
   at System.Configuration.Internal.InternalConfigHost.StaticOpenStreamForWrite(System.String, System.String, System.Object ByRef, Boolean)
   at System.Configuration.Internal.InternalConfigHost.System.Configuration.Internal.IInternalConfigHost.OpenStreamForWrite(System.String, System.String, System.Object ByRef, Boolean)
   at System.Configuration.Internal.InternalConfigHost.System.Configuration.Internal.IInternalConfigHost.OpenStreamForWrite(System.String, System.String, System.Object ByRef)
   at System.Configuration.ClientConfigurationHost.OpenStreamForWrite(System.String, System.String, System.Object ByRef)
   at System.Configuration.UpdateConfigHost.OpenStreamForWrite(System.String, System.String, System.Object ByRef)
   at System.Configuration.MgmtConfigurationRecord.SaveAs(System.String, System.Configuration.ConfigurationSaveMode, Boolean)

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.MgmtConfigurationRecord.SaveAs(System.String, System.Configuration.ConfigurationSaveMode, Boolean)
   at System.Configuration.Configuration.SaveAsImpl(System.String, System.Configuration.ConfigurationSaveMode, Boolean)
   at Microsoft.AppCenter.Utils.DefaultApplicationSettings.SaveValue(System.String, System.String)
   at Microsoft.AppCenter.Utils.DefaultApplicationSettings.SetValue(System.String, System.Object)
   at Microsoft.AppCenter.Utils.DefaultApplicationSettings.GetValue[[System.Guid, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String, System.Guid)
   at Microsoft.AppCenter.AppCenter.PlatformGetInstallIdAsync()
   at Microsoft.AppCenter.Utils.Constants.get_AppCenterFilesDirectoryPath()
   at Microsoft.AppCenter.Utils.Constants..cctor()

Exception Info: System.TypeInitializationException
   at Microsoft.AppCenter.Storage.Storage.DefaultAdapter()
   at Microsoft.AppCenter.AppCenter.InstanceConfigure(System.String)
   at Microsoft.AppCenter.AppCenter.PlatformStart(System.String, System.Type[])
   at AppCenterWPF.App.SetupAppCenter()
   at AppCenterWPF.App.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at AppCenterWPF.App.Main()


Faulting application name: AppCenterWPF.exe, version: 1.0.0.0, time stamp: 0xcbc73ca8
Faulting module name: KERNELBASE.dll, version: 10.0.18362.239, time stamp: 0xe665f337
Exception code: 0xe0434352
Fault offset: 0x00113442
Faulting process id: 0x5b94
Faulting application start time: 0x01d550606a31ebc9
Faulting application path: C:\Program Files\WindowsApps\9f64f8fa-ac6b-43cf-8709-464447b44c72_1.0.8.0_x64__mdpx8chr8ka72\AppCenterWPF\AppCenterWPF.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 23b395df-9c05-47a9-9b96-7dfab2a6abe8
Faulting package full name: 9f64f8fa-ac6b-43cf-8709-464447b44c72_1.0.8.0_x64__mdpx8chr8ka72
Faulting package-relative application ID: App
```

**Expected behavior**
Application to start

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Device: Surface Book 2
 - Version 1903 (Build 18362.239)

**Comment by keithrowe** [comment]
I'm seeing the same sequence of exceptions. Tried AppCenter.Start( ) for the first time. We also have a WPF app packaged in MSIX.

**Comment by annakocheshkova** [comment]
Hi there @PieEatingNinjas @keithrowe though we didn't manage to reproduce this, looks like there is an issue. I created a ticket to investigate this, we will keep you updated on the progress.

**Comment by annakocheshkova** [comment]
I'm a bit conserned of a way you call `trackEvent`. It requires passing a dictionary while what you pass might be interpreted as an array.
From official docs:
`Analytics.trackEvent('Video clicked', { Category: 'Music', FileName: 'favorite.avi' });`

**Comment by dhei** [comment]
Hey @PieEatingNinjas,

Thanks for reporting this issue with detailed repro steps. I was able to follow it through and got a repro with the same `System.UnauthorizedAccessException` error.

I believe the error is caused by a permission issue with the sandboxed MSIX-packaged WPF apps. If the app is not using MSIX, it should be fine.

```
Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.MgmtConfigurationRecord.SaveAs(System.String, System.Configuration.ConfigurationSaveMode, Boolean)
   at System.Configuration.Configuration.SaveAsImpl(System.String, System.Configuration.ConfigurationSaveMode, Boolean)
   at Microsoft.AppCenter.Utils.DefaultApplicationSettings.SaveValue(System.String, System.String)
   at Microsoft.AppCenter.Utils.DefaultApplicationSettings.SetValue(System.String, System.Object)
   at Microsoft.AppCenter.Utils.DefaultApplicationSettings.GetValue[[System.Guid, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String, System.Guid)
   at Microsoft.AppCenter.AppCenter.PlatformGetInstallIdAsync()
   at Microsoft.AppCenter.Utils.Constants.get_AppCenterFilesDirectoryPath()
   at Microsoft.AppCenter.Utils.Constants..cctor()
```
WPF SDK's [DefaultApplicationSettings class](https://github.com/microsoft/appcenter-sdk-dotnet/blob/6380fd1e52a770af875bf44426ec066a43c160f8/SDK/AppCenter/Microsoft.AppCenter.WindowsDesktop/Utils/DefaultApplicationSettings.cs#L67-L82) was trying to access System configuration which is inaccessible to MSIX-sandboxed WPF apps.

We will further investigate and update this thread when we have more to share.
